{{- range $key, $component := .Values.components }}
{{- if and $component.enabled $component.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "quickbite.componentName" (dict "root" $ "component" $component) }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "quickbite.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "quickbite.componentName" (dict "root" $ "component" $component) }}
  minReplicas: {{ $component.autoscaling.minReplicas }}
  maxReplicas: {{ $component.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $component.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
