{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quickbite.secretName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "quickbite.labels" . | nindent 4 }}
type: Opaque
stringData:
  identity-connection-string: {{ required "secrets.data.identityConnectionString is required when secrets.create=true" .Values.secrets.data.identityConnectionString | quote }}
  catalog-connection-string: {{ required "secrets.data.catalogConnectionString is required when secrets.create=true" .Values.secrets.data.catalogConnectionString | quote }}
  orders-connection-string: {{ required "secrets.data.ordersConnectionString is required when secrets.create=true" .Values.secrets.data.ordersConnectionString | quote }}
  payments-connection-string: {{ required "secrets.data.paymentsConnectionString is required when secrets.create=true" .Values.secrets.data.paymentsConnectionString | quote }}
  delivery-connection-string: {{ required "secrets.data.deliveryConnectionString is required when secrets.create=true" .Values.secrets.data.deliveryConnectionString | quote }}
  jwt-key: {{ required "secrets.data.jwtKey is required when secrets.create=true" .Values.secrets.data.jwtKey | quote }}
{{- end }}
